Initial scan with inconsistent stage in replication
ydb-platform/aardappel pull request #22
Opened 2024-08-22 09:23 UTC by VPolka

2024-08-27 10:39 UTC, dcherednik commented on internal/hb_tracker/hb_tracker.go
> +func (ht *HeartBeatTracker) GetMaxHb() types.HbData {
А тут не нужна прверка на GetReady()? Что если у нас есть патриции от которых мы еще не получили харбиты?

2024-08-27 10:43 UTC, dcherednik commented on internal/hb_tracker/hb_tracker.go
> +	for _, v := range ht.streams {
Это же по факту вызов GetQuorum()?

2024-08-27 10:52 UTC, dcherednik requested changes

2024-08-27 10:52 UTC, dcherednik commented on internal/processor/processor.go
> +func createReplicaStateTable(ctx context.Context, client table.Client, stateTablePath string, instanceId string) error {
Эти же функции теперь в main.

2024-08-27 10:52 UTC, dcherednik commented on internal/processor/processor.go
> +		return dst_table.PushQuery{}, 0, fmt.Errorf("Size of dstTables and tables in the tx mismatched",
Size of table?

2024-08-27 12:26 UTC, VPolka commented on internal/processor/processor.go
> +		return dst_table.PushQuery{}, 0, fmt.Errorf("Size of dstTables and tables in the tx mismatched",
Тут не очень поняла, я просто это место перенесла повыше в другую функцию

И кстати нет ли у нас тут бага, потому что если по 1 какой-нибудь табличке нет изменений никаких, то и дата транзакций в cdc нет, но это же не значит, что что-то не так?

2024-08-27 12:38 UTC, dcherednik commented on internal/processor/processor.go
> +		return dst_table.PushQuery{}, 0, fmt.Errorf("Size of dstTables and tables in the tx mismatched",
Я про нейминг. Не очень понятно о каком размере таблицы тут идет речь

2024-08-27 14:48 UTC, dcherednik commented on internal/processor/processor.go
> +func (processor *Processor) makeQuerysByTable(ctx context.Context, txs []types.TxData, dstTables []*dst_table.DstTable) (dst_table.PushQuery, int, error) {
Queries
by the way, what does byTable mean?

2024-08-27 14:56 UTC, dcherednik commented on internal/tx_queue/tx_queue.go
> +func (txQueue *TxQueue) PopTxsByCountAndHb(step uint64, maxCount int) []types.TxData {
Maybe PopTxsUntil?

2024-08-27 15:08 UTC, dcherednik commented on internal/processor/processor.go
> +func (processor *Processor) DoInitialScan(ctx context.Context, dstTables []*dst_table.DstTable,
Тут надо прям описать комментариями происходящее, при что то сделать с неймингом. Если бы я бы не знал идею я бы не понял что тут происходит.

2024-08-27 15:24 UTC, dcherednik commented on internal/processor/processor.go
> +		hb, err := processor.getSyncHbQuorum(ctx)
А оно сойдется? Я думал мы берем максимальный харбит в момент получения первого кворума, после чего ждем пока кворум достигнет этого харбита. Я не вижу кода ожидания кворума.

2024-08-29 13:22 UTC, dcherednik approved these changes

2024-08-29 14:34 UTC, merged